spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:~/users_account
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2